var asyncBase = require('./impl/asyncBase');
var config = require('./impl/config');
var PromiseProtocol = require('./impl/protocols/promise');
var Promise = require('./promise');
var CPS = require('./cps');
var Thunk = require('./thunk');
var Stream = require('./stream');
var Express = require('./express');
var Iterable = require('./iterable/index');

var async = asyncBase.mod({ protocol: PromiseProtocol });
async.config = config;
async.promise = Promise;
async.cps = CPS;
async.thunk = Thunk;
async.stream = Stream;
async.express = Express;
async.iterable = Iterable;
module.exports = async;
//# sourceMappingURL=index.js.map
